In [1]:
import cv2
 
def main():
    imgpath="C:\\Users\\SHAILESH SHAH\\Documents\\opencv\\misc\\4.1.01.tiff"
    img=cv2.imread(imgpath,1)
    print(img)
    print(type(img))
    print(img.dtype)
    print(img.shape)
    print(img.ndim)
    print(img.size)
    #outpath="C:\\Users\\SHAILESH SHAH\\Documents\\opencv\\output images\\4.1.01.tiff"
    
    cv2.namedWindow('Arina',cv2.WINDOW_AUTOSIZE)
    cv2.imshow('Arina',img)
    
    #cv2.imwrite(outpath,img)
    
    
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    #cv2.desytroyWindow('Arina')- deleting specified window
    
if __name__ == "__main__":
     main()

[[[ 42  46  52]
  [ 38  40  47]
  [ 34  42  50]
  ...
  [136 131 137]
  [136 137 126]
  [130 134 126]]

 [[ 43  45  55]
  [ 35  44  50]
  [ 38  40  54]
  ...
  [143 139 129]
  [139 134 129]
  [146 142 121]]

 [[ 39  42  46]
  [ 43  42  49]
  [ 55  42  52]
  ...
  [133 137 126]
  [130 131 123]
  [128 134 118]]

 ...

 [[  5   5   4]
  [  4   3   3]
  [  3   3   3]
  ...
  [ 44  64  60]
  [ 91  93  84]
  [ 93 105  98]]

 [[ 10   8  11]
  [ 12  11  12]
  [ 10  10  12]
  ...
  [ 40  68  60]
  [ 64  88  86]
  [ 91 105 100]]

 [[ 16  18  20]
  [ 16  16  19]
  [ 13  14  20]
  ...
  [ 42  56  55]
  [ 58  78  70]
  [ 80 100  93]]]
<class 'numpy.ndarray'>
uint8
(256, 256, 3)
3
196608


In [2]:
import cv2
 
def main():
    imgpath="C:\\Users\\SHAILESH SHAH\\Documents\\opencv\\misc\\4.1.01.tiff"
    img=cv2.imread(imgpath,0)
    print(img)
    print(type(img))
    print(img.dtype)
    print(img.shape)
    print(img.ndim)
    print(img.size)
    #outpath="C:\\Users\\SHAILESH SHAH\\Documents\\opencv\\output images\\4.1.01.tiff"
    
    cv2.namedWindow('Arina',cv2.WINDOW_AUTOSIZE)
    cv2.imshow('Arina',img)
    
    #cv2.imwrite(outpath,img)
    
    
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    #cv2.desytroyWindow('Arina')- deleting specified window
    
if __name__ == "__main__":
     main()

[[ 47  42  43 ... 133 134 131]
 [ 48  45  44 ... 136 133 136]
 [ 43  44  46 ... 133 128 129]
 ...
 [  5   3   3 ...  61  90 102]
 [  9  11  11 ...  62  85 102]
 [ 18  17  16 ...  54  73  96]]
<class 'numpy.ndarray'>
uint8
(256, 256)
2
65536
